### ISSUE TITLE
Broken npm package 0.0.3?

### ISSUE THREAD

**Issue by bobisjan** [jonathanKingston/eslint-config-nightmare-mode#1]
Hi,

I'm getting errors when running ember tests like this one:

`error  Rule 'no-comma-dangle' was removed and replaced by: comma-dangle no-comma-dangle`,

I have discovered that package at https://registry.npmjs.org/eslint-config-nightmare-mode/-/eslint-config-nightmare-mode-0.0.3.tgz contains old version of `eslint.json` (with `"no-comma-dangle": 2,`) compared with same file on GitHub.

Thanks

**Comment by bertdeblock** [comment]
I have the same issue, would be great if you could take a look at it.
Thanks in advance!

**Comment by blia** [comment]
+1

**Comment by jonathanKingston** [comment]
Super happy people are using this (Other feedback is welcome - more changes were planned before the 1.0.0 release).

The latest version is 0.3.0 which doesn't have this code in. It actually was released straight after 0.0.3.

Is there something depending on such an old version?

**Comment by bobisjan** [comment]
I do not use it directly so I can not specify desired version - I've updated `ember-cli-eslint` to `1.1.0`, then `brocolli-lint-eslint` resolved to `1.1.1` and `eslint-config-nightmare-mode` resolved to `0.0.3` - I do not why, but I also run `rm -rf node_modules` and `npm cache clean` to be sure...

BTW: Thanks for the eslint stuff for ember!

Update: I was confused with GitHub Releases, I've tried to update `ember-cli-eslint` to `1.2.1`, but still got `0.0.3` of this repo.

**Comment by bobisjan** [comment]
Sorry, I've overlooked that this repo is a dependency of `eslint-config-ember`, after updating this package everything look fine except hint errors :-).
