### ISSUE TITLE
ESLint 2.2/nightmare mode

### ISSUE THREAD

**Issue by chriskrycho** [jonathanKingston/eslint-config-nightmare-mode#2]
Just opening this as an easy place to discuss as I try to knock out the test fixes. :smile: 

Question: how far back do you want to support for node? (Translated: are you good with `let`, `const`, and `() => {...}`?)

**Edit:** I see that you actually have all those in the `tests` dir, so am proceeding under the assumption they're fair game. :smile:

**Comment by chriskrycho** [comment]
Note: it looks the failing tests are because of parsing errors, something in the interaction between ava and babel. More when I have it sorted!

**Edit:** I _believe_ what's happening is that the code samples aren't being processed by babel before being submitted to the ESLint checker. I'll pull in the Babel transforms to run before handing it to `eslint-code-review`, test it _that_ way, and then set up a PR assuming it works.

**Comment by jonathanKingston** [comment]
Yeah they shouldn't be the code should be linting for ES2015 syntax really... (not sure if I have required higher than that inadvertently).
To clarify I was too tired to fix this correctly so just dumped it onto github :grin:

Regarding node, my view is that all code can code through a transpiler for older nodes so it should be linted with the latest stable syntax. So the syntax you mention should be the preferred and is.

**Comment by chriskrycho** [comment]
Found the issue: it's [this change](http://eslint.org/docs/user-guide/migrating-to-2.0.0.html#language-options) to the behavior of ESLint. I'll tweak the rules for using ES6 and follow up.
